frontend:
  image: java:8-jre
  ports:
   - "8081:8081"
  volumes:
   - docker/volume-frontend:/frontend
   - docker/volume-log:/log
  command: ["java", "-jar", "-Done-jar.silent=true", "/frontend/FrontendApplication.jar", "server", "/frontend/config.yml"]

web:
  image: nginx
  links:
   - frontend
  ports:
   - "8080:80"
  volumes:
   - docker/volume-nginx-conf.d:/etc/nginx/conf.d
   - docker/volume-nginx-log:/var/log/nginx
