frontend:
  image: java:8-jre
  ports:
   - "8081:8081"
  volumes:
   - docker/volume-frontend:/frontend
   - docker/volume-log:/log
  command: ["java", "-jar", "-Done-jar.silent=true", "/frontend/FrontendApplication.jar", "server", "/frontend/config.yml"]

web:
  build: docker/image-nginx-lua/.
  links:
   - frontend
  ports:
   - "8080:8080"
  volumes:
   - docker/volume-nginx-conf.d:/opt/nginx/conf
   - docker/volume-log:/var/log/nginx
