server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 8083

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /log/authorisation.log
      archive: false
