server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8081

viewRendererConfiguration:
  .ftl:
    strict_syntax: yes
    whitespace_stripping: yes

logging:
  level: WARN
  appenders:
    - type: file
      currentLogFilename: /log/frontend.log
      archive: false
