server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8084

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /log/session.log
      archive: false
